#pragma once

#define MATRIX_ROWS 6
#define MATRIX_COLS 18

#define DIODE_DIRECTION COL2ROW

// --- SPLIT SETTINGS (TRRS SERIAL) ---
#define SPLIT_KEYBOARD
#define USE_SERIAL
#define SOFT_SERIAL_PIN GP1

#define MASTER_LEFT
